### PR TITLE
App Gallery

### PR DESCRIPTION
**Pull request by youngsun4786**

### CODE REVIEW

**Comment by yassine-moumen** [comment]
## To access Flojoy-studio build from this pull request, you can use the following URLs: 

Windows installation: http://649_windows.flojoy-test.com:3000 
Linux installation: http://649_linux.flojoy-test.com:3000 

Please note that it may take a few minutes for the instance to start up, so please be patient. 

It is important to know that the instance will automatically shut down after 4 hours to conserve resources. If you wish to start the instance again after it shuts down (or restart it to pickup new changes), you can use this API : 

Windows: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0e45dafb6dcfb5191&domain=649_windows 

Linux: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-03e1dd7ba106be757&domain=649_linux

**Comment by vinicvaz** [comment]
@youngsun4786 @yassine-moumen 
Could you help me to run a dev version locally? 
I was not able to run and visualize the app gallery locally.

**Comment by Jin1L** [comment]
> @youngsun4786 @yassine-moumen Could you help me to run a dev version locally? I was not able to run and visualize the app gallery locally.

It's fixed now!

**Review by itsjoeoui — APPROVED** [review]
lgtm

**Pull request merged**
