### PR TITLE
Develop local (Angel)

### PR DESCRIPTION
**Pull request by Angchau**
Modify App.json for Camera and Single Serial -- Added Text node with link to the docs section 

-Question: Is it possible to create a working link within the Text node?

### CODE REVIEW

**Review by JeffDotPng — APPROVED** [review]
Looks good

**Review by JeffDotPng — CHANGES_REQUESTED** [review]
Actually, since there were extra parameters on the Keithley node I need you to update the app again with the updated parameters after you change the node (just delete the node and add it again)

**Comment by Angchau** [comment]
Normally the requested changes are done !!

**Review by JeffDotPng — APPROVED** [review]
lgtm

**Pull request merged**
