### PR TITLE
app icon now displays on dock

### PR DESCRIPTION
**Pull request by youngsun4786**

### CODE REVIEW

**Comment by smahmed776** [comment]
I got the following error running on my Windows:
Screenshot 2023-08-14 191557

**Comment by Jin1L** [comment]
It is not currently working on the Window environment

**Comment by youngsun4786** [comment]
> I got the following error running on my Windows: Screenshot 2023-08-14 191557

Hey @smahmed776 aw man I knew it would happen

**Comment by itsjoeoui** [comment]
@youngsun4786 ping me on slack once it is fixed please!

**Comment by youngsun4786** [comment]
> @youngsun4786 ping me on slack once it is fixed please!

I will for sure. I've been trying to get the icons configured during build time instead

**Review by smahmed776 — APPROVED** [review]

**Review by itsjoeoui — APPROVED** [review]
lgtm

**Pull request merged**
